# Generated by Django 2.0.3 on 2019-03-30 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('timestampOfExpense', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Expenses.Client')),
            ],
            options={
                'verbose_name': 'Expenses',
                'verbose_name_plural': 'Expenses',
                'ordering': ['timestampOfExpense'],
            },
        ),
    ]
